global:
  security:
    allowInsecureImages: true
  imageRegistry: "public.ecr.aws"


mysql:
  architecture: replication
  image:
    registry: "public.ecr.aws"
    repository: bitnami/mysql
    tag: 8.0.40-debian-12-r5
  auth:
    existingSecret: "mysql-passwords"
    database: "my-database"
    username: "my-user"

  primary:
    nodeSelector:
      database-location: "node-1"
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: macvlan-db-net   # Multus secondary network
    persistence:
      enabled: true
      size: 8Gi
    startupProbe:
      enabled: false
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false  

  secondary:
    replicaCount: 1                   
    nodeSelector:
      database-location: "node-2"
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: macvlan-db-net
    persistence:
      enabled: true
      size: 8Gi
    startupProbe:
      enabled: false  
    readinessProbe:
      enabled: false   
    livenessProbe:
      enabled: false  

webserver:
  replicaCount: 3
  image: nginx:1.29-alpine
  port: 80
  name: webserver
  configMapName: web-config


initcontainer:
  name: init-serving-host
  image: busybox:1.28


service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080