apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "webserver.fullname" . }}
    role: webserver
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}